pipeline {
  environment {
    registry = "anandraman7978/jenkins-docker2"
    registryCredential = 'anandraman7978'
  }
  agent any
  stages {
    stage('Cloning Git') {
      steps {
        git 'https://github.com/anandraman7978/capstone.git'
      }
    }
    stage ('Initialize') {
      steps {
        echo 'Placeholder.'
      }
    }
    stage('Build Docker Image') {
   steps {
    withCredentials([[$class: 'UsernamePasswordMultiBinding', credentialsId: 'anandraman7978', usernameVariable: 'DOCKER_USERNAME', passwordVariable: 'DOCKER_PASSWORD']]){
     sh './run_docker.sh'
    }
   }
  }
    stage('Deploy Image') {
        steps {
        withCredentials([[$class: 'UsernamePasswordMultiBinding', credentialsId: 'anandraman7978', usernameVariable: 'DOCKER_USERNAME', passwordVariable: 'DOCKER_PASSWORD']]){
     sh './upload_docker.sh'
    
    }
    }
    }
           

    
  }
}
